// <auto-generated />
using System;
using BookingHomestay.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace BookingHomestay.Infrastructure.Migrations
{
    [DbContext(typeof(BookingHomestayDbContext))]
    [Migration("20240424034240_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookingHomestay.Domain.Entities.CommonEnities.Photo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BookingHomestay.Domain.Entities.Room.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Area = 100.0,
                            Description = "Homestay gia re",
                            Price = 500000m,
                            Title = "Tam An Homestay",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Area = 260.0,
                            Description = "Homestay gia re",
                            Price = 450000m,
                            Title = "ChocoHouse",
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Area = 400.0,
                            Description = "Homestay gia re",
                            Price = 350000m,
                            Title = "Dory Homestay",
                            UserID = 3
                        },
                        new
                        {
                            ID = 4,
                            Area = 800.0,
                            Description = "Homestay gia re",
                            Price = 220000m,
                            Title = "The Dreamers Homestay",
                            UserID = 4
                        });
                });

            modelBuilder.Entity("BookingHomestay.Domain.Entities.RoomAggregate.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookingHomestay.Domain.Entities.RoomAggregate.Province", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("CategoryRoom", b =>
                {
                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.Property<int>("RoomsID")
                        .HasColumnType("int");

                    b.HasKey("CategoriesID", "RoomsID");

                    b.HasIndex("RoomsID");

                    b.ToTable("CategoryRoom");
                });

            modelBuilder.Entity("BookingHomestay.Domain.Entities.CommonEnities.Photo", b =>
                {
                    b.HasOne("BookingHomestay.Domain.Entities.Room.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingHomestay.Domain.Entities.Room.Room", b =>
                {
                    b.HasOne("BookingHomestay.Domain.Entities.RoomAggregate.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID");

                    b.OwnsOne("BookingHomestay.Domain.Entities.Room.Address", "Address", b1 =>
                        {
                            b1.Property<int>("RoomID")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCare")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RoomID");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomID");

                            b1.HasData(
                                new
                                {
                                    RoomID = 1,
                                    AddressLine1 = "56 Kiet 93 An Duong Vuong",
                                    AddressLine2 = "Thanh pho Hue, Tinh Thua Thien Hue",
                                    City = "Hue",
                                    PostalCare = "49000"
                                },
                                new
                                {
                                    RoomID = 2,
                                    AddressLine1 = "20 Nguyễn Tri Phương",
                                    AddressLine2 = "Phường Phú Nhuận, Thành phố Huế, Tỉnh Thừa Thiên Huế",
                                    City = "Hue",
                                    PostalCare = "49000"
                                },
                                new
                                {
                                    RoomID = 3,
                                    AddressLine1 = "73 Thạch Hãn",
                                    AddressLine2 = "Thanh pho Hue, Tinh Thua Thien Hue",
                                    City = "Hue",
                                    PostalCare = "49000"
                                },
                                new
                                {
                                    RoomID = 4,
                                    AddressLine1 = "106 Hải Triều",
                                    AddressLine2 = "Thanh pho Hue, Tinh Thua Thien Hue",
                                    City = "Hue",
                                    PostalCare = "49000"
                                });
                        });

                    b.OwnsOne("BookingHomestay.Domain.Entities.RoomAggregate.Location", "Location", b1 =>
                        {
                            b1.Property<int>("RoomID")
                                .HasColumnType("int");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<Point>("LocationPoint")
                                .HasColumnType("geography");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("PlaceID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RoomID");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomID");

                            b1.HasData(
                                new
                                {
                                    RoomID = 1,
                                    Latitude = 16.452226317000054,
                                    Longitude = 107.60572747100008,
                                    PlaceID = ""
                                },
                                new
                                {
                                    RoomID = 2,
                                    Latitude = 16.464479972000049,
                                    Longitude = 107.59203459400004,
                                    PlaceID = ""
                                },
                                new
                                {
                                    RoomID = 3,
                                    Latitude = 16.471000728000035,
                                    Longitude = 107.57140013500003,
                                    PlaceID = ""
                                },
                                new
                                {
                                    RoomID = 4,
                                    Latitude = 16.455358346983619,
                                    Longitude = 107.6071873579871,
                                    PlaceID = ""
                                });
                        });

                    b.Navigation("Address");

                    b.Navigation("Location");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CategoryRoom", b =>
                {
                    b.HasOne("BookingHomestay.Domain.Entities.RoomAggregate.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingHomestay.Domain.Entities.Room.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
